# Generated by Django 5.2.7 on 2025-12-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_merge_20251124_1554'),
        ('elements', '0005_remove_contratoselement_status'),
    ]

    operations = [
    ]
