# Generated by Django 5.2.7 on 2025-12-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_adiciona_status_e_objeto_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoselement',
            name='status_pagamento',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20, verbose_name='Status de Pagamento'),
        ),
    ]
