# Generated by Django 5.2.7 on 2025-12-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_contratoselement_status_pagamento'),
        ('elements', '0006_merge_20251217_1125'),
    ]

    operations = [
    ]
