# Generated by Django 5.2.7 on 2025-12-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_merge_20251217_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoselement',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratoselement',
            name='objeto',
            field=models.TextField(default='Objeto não informado'),
        ),
    ]
