# Generated by Django 6.0.1 on 2026-01-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_contratoselement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoselement',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ'),
        ),
    ]
